<option value="31">Biała Podlaska</option>
<option value="173">Białystok</option>
<option value="174">Bielsk Podlaski</option>
<option value="155">Bielsko-Biała</option>
<option value="5">Bolesławiec</option>
<option value="13">Brodnica</option>
<option value="84">Brzeg</option>
<option value="112">Busko</option>
<option value="14">Bydgoszcz</option>
<option value="154">Będzin</option>
<option value="32">Chełm</option>
<option value="157">Chorzów</option>
<option value="70">Ciechanów</option>
<option value="178">Człuchów</option>
<option value="158">Częstochowa</option>
<option value="106">Elbląg</option>
<option value="107">Ełk</option>
<option value="71">Garwolin</option>
<option value="179">Gdańsk</option>
<option value="181">Gdynia</option>
<option value="108">Giżycko</option>
<option value="159">Gliwice</option>
<option value="40">Gorzów Wlkp</option>
<option value="15">Grudziądz</option>
<option value="1">Głogów</option>
<option value="16">Inowrocław</option>
<option value="89">Jarosław</option>
<option value="90">Jasło</option>
<option value="42">Kalisz</option>
<option value="161">Katowice</option>
<option value="150">Kielce</option>
<option value="97">Konin</option>
<option value="24">Koszalin</option>
<option value="23">Kołobrzeg</option>
<option value="63">Kraków</option>
<option value="2">Kłodzko</option>
<option value="85">Kędzierzyn</option>
<option value="98">Leszno</option>
<option value="109">Lidzbark Warmiński</option>
<option value="35">Lublin</option>
<option value="53">Łódź</option>
<option value="182">Malbork</option>
<option value="168">Mielec</option>
<option value="74">Mińsk Mazowiecki</option>
<option value="169">Nisko</option>
<option value="66">Nowy Sącz</option>
<option value="67">Nowy Targ</option>
<option value="99">Nowy Tomyśl</option>
<option value="110">Olsztyn</option>
<option value="88">Opole</option>
<option value="111">Ostróda</option>
<option value="77">Ostrołęka</option>
<option value="68">Oświęcim</option>
<option value="101">Piła</option>
<option value="102">Poznań</option>
<option value="37">Puławy</option>
<option value="79">Płock</option>
<option value="81">Radom</option>
<option value="163">Rybnik</option>
<option value="171">Rzeszów</option>
<option value="152">Sandomierz</option>
<option value="172">Sanok</option>
<option value="82">Siedlce</option>
<option value="57">Sieradz</option>
<option value="58">Skierniewice</option>
<option value="25">Stargard Szczeciński</option>
<option value="176">Suwałki</option>
<option value="27">Szczecin</option>
<option value="26">Szczecinek</option>
<option value="185">Słupsk</option>
<option value="28">Świnoujście</option>
<option value="69">Tarnów</option>
<option value="59">Tomaszów Mazowiecki</option>
<option value="18">Toruń</option>
<option value="165">Tychy</option>
<option value="91">Warszawa-Mokotów</option>
<option value="92">Warszawa-Ochota</option>
<option value="93">Warszawa-Praga</option>
<option value="95">Warszawa-Śródmieście</option>
<option value="10">Wrocław</option>
<option value="83">Wyszków</option>
<option value="30">Włocławek</option>
<option value="38">Zamość</option>
<option value="50">Zielona Góra</option>
<option value="175">Łomża</option>
<option value="51">Żagań</option>
