USE `irk`;
TRUNCATE `kandydat_dane_adresowe`;
TRUNCATE `kandydat_dane_osobowe`;
TRUNCATE `kandydat_kierunki_wybrane_punkty_rankingowe`;
TRUNCATE `kandydat_olimpiady`;
TRUNCATE `kandydat_wyniki_maturalne`;
TRUNCATE `kwalifikacje`;
TRUNCATE `login`;
 -- TRUNCATE `slownik_olimpiad_przedmiotowych`;
 -- TRUNCATE `slownik_przedmiotow_maturalnych`;
TRUNCATE `zdjecia`;
TRUNCATE `eventlog`;
TRUNCATE `mailkonta`;
TRUNCATE `snc1k`;
TRUNCATE `snc2k`;
TRUNCATE `snc2kis`;
TRUNCATE `ssc1k`;
TRUNCATE `ssc2k`;
TRUNCATE `ssc2kis`;
TRUNCATE `ssw1k`;
TRUNCATE `ssw2k`;
TRUNCATE `ssw2kis`;
